// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession()
    let session = data.session
    const expiresAt = (session?.expires_at ?? 0) * 1000
    if (session && expiresAt && expiresAt <= Date.now() + 2 * 60_000) {
      const { data: refreshed } = await supabase.auth.refreshSession()
      session = refreshed.session ?? session
    }
    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
