// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


type PublicRuntimeConfig = {
  supabaseUrl?: string;
  supabasePublishableKey?: string;
  supabaseProjectId?: string;
};

declare global {
  interface Window {
    __OBAIDA_PUBLIC_CONFIG__?: PublicRuntimeConfig;
  }
}

function createSupabaseClient() {
  const runtimeConfig =
    typeof window !== 'undefined' ? window.__OBAIDA_PUBLIC_CONFIG__ : undefined;
  const serverEnv = typeof process !== 'undefined' ? process.env : undefined;
  const SUPABASE_PROJECT_ID =
    import.meta.env.VITE_SUPABASE_PROJECT_ID ||
    runtimeConfig?.supabaseProjectId ||
    serverEnv?.SUPABASE_PROJECT_ID;
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    runtimeConfig?.supabaseUrl ||
    serverEnv?.SUPABASE_URL ||
    (SUPABASE_PROJECT_ID ? `https://${SUPABASE_PROJECT_ID}.supabase.co` : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.VITE_SUPABASE_ANON_KEY ||
    runtimeConfig?.supabasePublishableKey ||
    serverEnv?.SUPABASE_PUBLISHABLE_KEY ||
    serverEnv?.SUPABASE_ANON_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase public configuration: ${missing.join(', ')}. Configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY at build time, or SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY on the server.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
